import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from "./providers";
import { getUserOnServer } from "./(auth)/session/route";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export const preferredRegion = "home";

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  const user = await getUserOnServer();
  return (
    <html lang={process.env.NEXT_PUBLIC_GLOBAL_LANG}>
      <body className={inter.className}>
        <div className="flex flex-col">
          <Providers user={user}>{children}</Providers>
        </div>
      </body>
    </html>
  );
}
