/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/

declare module "zapatos/custom" {
	/**
	 * Org roles to determine who can admin the org and who can specific things within the org
	 */
	export type PgOrgRole =
		| "admin"
		| "admin.user"
		| "admin.user.read"
		| "admin.user.write"
		| "admin.user.delete";
}
