/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { components } from "@/components/sections";

declare module "zapatos/custom" {
	export type PgPageSectionCode =
		// hero
		| "HE001"
		// image
		| "IMG001"
		// image text
		| "IT001"
		// text
		| "H001"
		| "T001"
		// video
		| "VDO001"
		// text grid
		| "TG001";
}
