/*
** Please edit this file as needed **
It's been generated by Zapatos as a custom type definition placeholder, and won't be overwritten
*/
import type { components } from "@/components/sections";

declare module "zapatos/custom" {
	export type PgPageSectionCode = keyof typeof components;
}
